### ISSUE TITLE
[Feature Request] Suffix Textcolors

### ISSUE THREAD

**Issue by MisterCookie1234** [WiIIiam278/HuskChat#22]
Hello.

I'd like to be able to attach suffixes to Groups, that are able to change the Textcolor, like here: 

![image](https://user-images.githubusercontent.com/24813669/159170549-39b0d66b-d586-4837-801d-b426a27830aa.png)

**Comment by MalzSmith** [comment]
You can already somewhat do this by changing the format for the channel

For example setting a group suffix to `&c` and using a config like this will cause the messages to be red.
```
global:
    format: '%prefix%&r&f[<%name%>](suggest_command=/msg %name% ):%suffix% '
    broadcast_scope: GLOBAL
    log_to_console: true
    shortcut_commands:
    - /global
    - /g
```

You can also use MineDown in the suffix and it will apply to the message. This is probably not intended and is caused by how the ComponentBuilder in Bungeecord works. It's been like this forever.
