### ISSUE TITLE
%channel% placeholder not being replaced in Local spy messages

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskChat#71]
![image](https://user-images.githubusercontent.com/31187453/181634830-7e3a35d4-a8fc-4f4a-bd9f-2b46fe7d2489.png)

**Comment by Ceddix** [comment]
Now it just looks like this:
![image](https://user-images.githubusercontent.com/49922771/214916062-1f149a3b-4815-4ad2-9b72-63486e3e12a0.png)
But it still doesn't display the server 🤔 

My config looks like this:
```
local_spy:
  enabled: true
  format: '&e[Spy] &7[%channel%] %fullname%&8:%spy_color% '
  localspy_aliases:
    - /localspy
    - /ls
```
