### ISSUE TITLE
formatting codes at the end of message format settings aren't set

### ISSUE THREAD

**Issue by Ceddix** [WiIIiam278/HuskChat#98]
In the `config.yml` of HuskChat you have the possibility to change the format of some messages/channels (e.g. under `channels.<channel>.format` or `message_command.format`).

Previously, if there was a formatting code at the end of this string, it was used for the message that followed. But this isn't the case anymore.

For example, my config looks like this:
```
channels:
  staff:
    format: '&c+++ %fullname%&f:&c '
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      send: 'huskchat.channel.adminchat.send'
      receive: 'huskchat.channel.adminchat.receive'
    shortcut_commands:
      - /ac
```
But the output looks like this:
![image](https://user-images.githubusercontent.com/49922771/214914776-7665eb21-54b2-41ed-8b59-24428f2019ae.png)

It seems like the message simply doesn't get formatted (`&r`).

The error should be somewehere [here](https://github.com/WiIIiam278/HuskChat/blob/master/common/src/main/java/net/william278/huskchat/message/MessageManager.java#L110-L180), because the message is just appended so I guess the format doesn't get applied to it.
