### ISSUE TITLE
channel permission does not work when the Luckperms context is set

### ISSUE THREAD

**Issue by dawnTak** [WiIIiam278/HuskChat#99]
Hello! I have a situation while using the plugin
Bungeecord server, When context is set for channel permission, Permission check is not work.
For example huskchat.channel.lobby.send true server=lobby
Detects correctly when no context is set
Whatever players inherit permissions or give permission
[I used a translator, sorry]

![20230209020420](https://user-images.githubusercontent.com/123202334/217615336-8feb2620-0299-40db-ba87-f2ceb58423d1.png)

```
lobby:
    format: "&r&f%fullname%&r&7: &r"
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      send: huskchat.channel.lobby.send
      receive: huskchat.channel.lobby.receive
    restricted_servers:
    - skyblock
```

Server version 1.19.3, HuskChat-2.4.1, Luckperms installation in proxies and servers use mysql
Thank you so much!
